webpos:
  jwt:
    location: classpath:webpos.jks
    password: 123456
    tokenTTL: 30m
  auth:
    excludePaths:
      - /**
server:
  port: 8086
spring:
  application:
    name: user
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost